# ACQ_REGULAR_PRFX
# STATION NAME (hostname)
# Telescope sempre uguale??
# SITELAT
# EVEV
# LONG
# ****
# rsync al momento attivo
# trasferire i dati nella cartella prisma data
# cleaning
# autenticazione 
# ---
# comando semplice!!!!
# ***
