---
- name: deploy_server
  hosts: server
  vars:
    mode: "server"
    prometheus_scrape_configs:
    - job_name: "prometheus"
      static_configs:
        - targets:
            - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"
    - job_name: "node"
      static_configs:
        - targets:
            - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9100"
            - 10.8.0.8:9100
  become: true
  become_method: sudo
  become_flags: '-E -S -n'
  roles:
    - updatehosts
    - docker
    - node_exporter
    - prometheus
