---
- name: deploy_server
  hosts: server
  vars:
    mode: "server"
    sync_servers:
    - 10.8.0.8
  become: true
  become_method: sudo
  become_flags: '-E -S -n'
  roles:
    - updatehosts
    - docker
    - node_exporter
    - prometheus
    - server-automation
