---
- name: deploy_server
  hosts: server
  vars:
    mode: "server"
  become: true
  become_method: sudo
  become_flags: '-E -S -n'
  roles:
    - updatehosts
    - docker
    - node_exporter
    - prometheus
