---
- name: deploy_st001 # prisma test camera NUC Torino
  hosts: client
  vars:
    mode: "client"
  become: true
  become_method: sudo
  become_flags: '-E -S -n'
  roles:
    - node_exporter
    - freeture
    - VPN
