## set up the compression
- name: Copy up compress.py file
  copy:
    src: "{{ role_path }}/code/compress.py"
    dest: "/usr/local/bin/compress.py"

- name: Add cron job for compression
  cron:
    name: "Compress prisma data at {{data_path}}"
    minute: "30"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    user: "root"
    job: "python3 /usr/local/bin/compress.py -r {{data_path}} -o {{rsync_data_path}}"
    cron_file: "/etc/crontab"
  become: yes
  with_items: "{{ sync_servers }}"

