# ACQ_REGULAR_PRFX
# STATION NAME (hostname)
# Telescope sempre uguale??
# SITELAT
# EVEV
# LONG
# ****
# rsync al momento attivo
# trasferire i dati nella cartella prisma data
# cleaning
# autenticazione 
# ---
# comando semplice!!!!
# ***
- name: Install the NTP daemon to synchronize the clocks to ms.
  apt: name=ntp

- name: Install dependencies
  apt:
    name:
    - ntp
    - openvpn
    - freeture
    update_cache: yes

- name: Make sure ntp is started, and is enabled on restart.
  service: name=ntp state=started enabled=yes

- name: Set the timezone to the {{ntp_timezone}} one
  timezone: "name={{ntp_timezone}}"

- name: Add ssh key
  lineinfile:
    line: "{{ item }}"
    dest: ~/.ssh/authorized_keys
    regex: "{{ item.split()[1] | regex_escape() }}" # use the hash to match
    create: no
    mode: 0600
  with_items: "{{ add_ssh_keys }}"

- name: Generate freeture configuration
  become: true
  template:
    src: "{{ playbook_dir }}/roles/freeture/templates/configuration.cfg.j2"
    dest: /etc/freeture/configuration.cfg
    force: true
    mode: 0755

- name: Create freeture service configuration directory
  file:
    path: /etc/systemd/system/freeture.service.d
    state: directory
    mode: 0755

- name: Fix node_exporter service configuration
  become: true
  template:
    src: "{{ playbook_dir }}/roles/node_exporter/templates/freeture.conf.j2"
    dest: /etc/systemd/system/freeture.service.d/freeture.conf
    force: true
    mode: 0755
  notify: restart freeture