# ACQ_REGULAR_PRFX
# STATION NAME (hostname)
# Telescope sempre uguale??
# SITELAT
# EVEV
# LONG
# ****
# rsync al momento attivo
# trasferire i dati nella cartella prisma data
# cleaning
# autenticazione 
# ---
# comando semplice!!!!
# ***
- name: Mount DVD read-only
  become: yes
  mount:
    path: /prismadata
    src: /dev/sda1
    state: mounted
    fstype: ext4

- name: Change file ownership, group and permissions
  become: yes
  file:
    path: /etc/resolv.conf
    mode: o+r 

- name: Install dependencies
  become: yes
  apt:
    name:
    - ntp
    - freeture
    update_cache: yes

- name: Make sure ntp is started, and is enabled on restart.
  service: name=ntp state=started enabled=yes

- name: Set the timezone to the {{ntp_timezone}} one
  timezone: "name={{ntp_timezone}}"

- name: Add ssh key
  become: yes
  lineinfile:
    line: "{{ item }}"
    dest: ~/.ssh/authorized_keys
    regex: "{{ item.split()[1] | regex_escape() }}" # use the hash to match
    create: no
    mode: 0600
  with_items: "{{ add_ssh_keys }}"

- name: Ensure freeture data directory
  file:
    path: '/etc/freeture/'
    state: directory
    mode: 0755
  become: yes

- name: Generate freeture configuration
  become: true
  template:
    src: "{{ playbook_dir }}/roles/freeture/templates/configuration.cfg.j2"
    dest: /etc/freeture/configuration.cfg
    force: true
    mode: 0755

- name: Create freeture service configuration directory
  file:
    path: /etc/systemd/system/freeture.service.d
    state: directory
    mode: 0755



- name: Fix freeture service configuration
  become: true
  template:
    src: "{{ playbook_dir }}/roles/freeture/templates/freeture.conf.j2"
    dest: /etc/systemd/system/freeture.service
    force: true
    mode: 0755
  notify: restart freeture