---
- name: Install node_exporter for Debian
  become: true
  block:

    - name: Install prometheus-node-exporter
      apt:
        deb: "{{ node_exporter_apt_package }}"

    - name: Create node_exporter service configuration directory
      file:
        path: /etc/systemd/system/prometheus-node-exporter.service.d
        state: directory
        mode: 0755

    - name: Fix node_exporter service configuration
      template:
        src: "{{ playbook_dir }}/roles/node_exporter/templates/prometheus-node-exporter.conf.j2"
        dest: /etc/systemd/system/prometheus-node-exporter.service.d/prometheus-node-exporter.conf
        force: true
        mode: 0755
      notify: restart prometheus-node-exporter

- meta: flush_handlers