- name: Install cron
  become: yes
  apt:
    pkg:
      - cron
    state: present
    update_cache: yes

- name: Ensure prismadata directory
  file:
    path: '/prismadata/'
    state: directory
    mode: 0755
  become: yes

- name: Add cron job
  cron:
    name: "{{ cron_job_name }}"
    minute: "{{ cron_job_minute }}"
    hour: "{{ cron_job_hour }}"
    day: "{{ cron_job_day }}"
    month: "{{ cron_job_month }}"
    weekday: "{{ cron_job_weekday }}"
    user: "{{ cron_job_user }}"
    job: "rsync -av --ignore-existing  {{item}}"
    cron_file: "{{ cron_file }}"
  become: yes
  with_items: "{{ sync_servers }}"
