- name: git PRISMA_Automation
  ansible.builtin.git:
    repo: https://github.com/Matteo04052017/PRISMA_automation.git
    dest: /src/PRISMA_automation
  environment:
    GIT_TERMINAL_PROMPT: 0 

- name: replace server ip
  ansible.builtin.replace:
    path: {{item}}
    regexp: '172.29.144.1'
    replace: '{{server_ip}}'
  with_items: 
    - /src/PRISMA_automation/docker/driver/procedures_config.json
    - /src/PRISMA_automation/docker/www_files/config.php

- name: build PRISMA_Automation docker images
  community.general.make:
    chdir: /src/PRISMA_automation
    target: build

- name: start PRISMA_Automation
  community.general.make:
    chdir: /src/PRISMA_automation
    target: start