- name: Install cron
  become: yes
  apt:
    pkg:
      - cron
    state: present
    update_cache: yes

- name: Copy up PRISMA_Automation files
  become: yes 
  synchronize:
    src: "{{ role_path }}/PRISMA_Automation/"
    dest: "/usr/local/bin/PRISMA_Automation/"

- name: Copy up data on camera files
  become: yes 
  synchronize:
    src: "{{ role_path }}/data/"
    dest: "/usr/local/bin/PRISMA_Automation/data/"

- name: Add cron job
  cron:
    name: "{{ cron_job_name }}-{{item}}"
    minute: "{{ cron_job_minute }}"
    hour: "{{ cron_job_hour }}"
    day: "{{ cron_job_day }}"
    month: "{{ cron_job_month }}"
    weekday: "{{ cron_job_weekday }}"
    user: "{{ cron_job_user }}"
    job: "python3 /usr/local/bin/PRISMA_Automation/sync_camera.py --input_json_file=data/camera_to_sync.json -d 5"
    cron_file: "{{ cron_file }}"
  become: yes
