
- name: Ensure grafana provisioning directory
  file:
    path: '{{ grafana_provisioning_config_dir }}/datasources'
    state: directory
    mode: 0755
    owner: "{{ localuser }}"
    group: "{{ localuser }}"
  become: yes

- name: Ensure grafana data directory
  file:
    path: '{{ grafana_data }}'
    state: directory
    mode: 0755
    owner: "{{ localuser }}"
    group: "{{ localuser }}"
  become: yes

- name: Generate Prometheus datasource on grafana
  become: true
  template:
    src: "{{ playbook_dir }}/roles/prometheus/templates/datasource.yaml.j2"
    dest: "{{ grafana_provisioning_config_dir }}/datasources/datasource.yaml"
    force: true
    owner: "{{ localuser }}"
    group: "{{ localuser }}"
    mode: 0755

- name: Pull grafana image {{ grafana_docker_tags }}
  docker_image:
    name: grafana/grafana
    tag: "{{ grafana_docker_tags }}"

- name: Stop grafana container
  docker_container:
    name: grafana
    state: absent

- name: Start grafana container
  docker_container:
    name: grafana
    image: "grafana/grafana:{{ grafana_docker_tags }}"
    state: started
    user: root
    restart: yes
    restart_policy: always
    ports:
     - "3000:3000"
    volumes:
      - "{{ grafana_provisioning_config_dir }}:/etc/grafana/provisioning"
      - "{{ grafana_data }}:/var/lib/grafana"
      - "/etc/hosts:/etc/hosts:ro"
    env:
      GF_INSTALL_PLUGINS: "{{ grafana_plugins|join(',') }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password }}"

- name: nodexporter-dashboard make sure grafana configuration directories exist
  become: true
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "/etc/grafana/provisioning/datasources"
    - "/etc/grafana/provisioning/dashboards/node-exporter-dashboard"
    - "/etc/grafana/provisioning/notifiers"

- name: nodexporter-dashboard Copy up resource files
  become: true
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/etc/grafana/provisioning/dashboards/node-exporter-dashboard/{{ item }}"
  with_items:
    - node-exporter.json

- name: nodexporter-dashboard Write dashboards provisioning config file
  become: true
  template:
    src: dashboards-nodexporter-dashboard.yml.j2
    dest: /etc/grafana/provisioning/dashboards/nodexporter-dashboard.yml
    mode: 0640
