---
- name: restart freeture
  service:
    name: freeture
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: true

- name: restart networking
  service:
    name: networking
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: true